spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

<<<<<<< HEAD
<<<<<<< Updated upstream
    url: jdbc:mysql://localhost:3306/
    username: root
    password: 1226
=======
#<<<<<<< Updated upstream:BoardSE/src/main/resources/application.yaml
    url: jdbc:mysql://localhost:3306/narae
    username: root
    password: 1226
#=======
#<<<<<<< Updated upstream
#    url: jdbc:mysql://localhost:3306/board
#    username: root
#    password: system
#=======
#    url: jdbc:mysql://localhost:3306/olleh
#    username: root
#    password: zhtanf5246150!

  #>>>>>>> Stashed changes
#>>>>>>> Stashed changes:Board/src/main/resources/application.yaml

#
#>>>>>>> Stashed changes
>>>>>>> Stashed changes
=======
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: system
>>>>>>> main

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
jwt:
  token:
    secret: "secretKey2G312A3E224A78H51R6dfvnjhgSf3asD3N5KE23Lq"
  access-expired: 3600000    #3600000 1시간
  refresh-expired: 86400000   # 1 day

server:
  port: 8081

#  org.hibernate.type: trace