spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#<<<<<<< Updated upstream

#<<<<<<< Updated upstream:BoardSE/src/main/resources/application.yaml
#    url: jdbc:mysql://localhost:3306/ollehboard
#    username: root
#    password: 0903
#=======
#<<<<<<< Updated upstream
#    url: jdbc:mysql://localhost:3306/board
#    username: root
#    password: system
#=======
    url: jdbc:mysql://localhost:3306/olleh
    username: root
    password: zhtanf5246150!

  #>>>>>>> Stashed changes
#>>>>>>> Stashed changes:Board/src/main/resources/application.yaml

#
#>>>>>>> Stashed changes

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
jwt:
  token:
    secret: "secretKey2G312A3E224A78H51R6dfvnjhgSf3asD3N5KE23Lq"
  access-expired: 3600000    #3600000 1시간
  refresh-expired: 86400000   # 1 day

logging.level:
  org.hibernate.SQL: debug

#  org.hibernate.type: trace