spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost:3306/ollehboard
    username: root
    password: system

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  redis:
    host: localhost
    port: 6379
jwt:
  token:
    secret: "secretKey2G312A3E224A78H51R6dfvnjhgSf3asD3N5KE23Lq"
  access-expired:  3600000 #1시간  #6000 5초
  refresh-expired: 86400000   # 1 day


server:
  port: 8080


logging.level:
  org.hibernate.SQL: debug

upload:
  path: C:\Users\zhscl\Desktop\LocalImageRepository